# Generated by Django 4.1.5 on 2023-02-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auctionitem',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auctionitem',
            field=models.ManyToManyField(to='auctions.auctionlisting'),
        ),
    ]
