# Generated by Django 4.1.5 on 2023-02-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_watchlist_auctionitem_watchlist_auctionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auctionitem',
            field=models.ManyToManyField(related_name='auction_listing', to='auctions.auctionlisting'),
        ),
    ]
